# Form implementation generated from reading ui file 'Thong_ke_diem.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1193, 728)
        Form.setStyleSheet("#Thongke_frame{\n"
"    border-radius: 10px;\n"
"    border:none;\n"
"    background-color:#fff;\n"
"}\n"
"\n"
"#chon_nam_frame{\n"
"    background-color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#Bieudo_frame{\n"
"    background-color: #fff;\n"
"    border:none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#diemtop_bot_frame{\n"
"    background-color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.Thongke_frame = QtWidgets.QFrame(parent=Form)
        self.Thongke_frame.setGeometry(QtCore.QRect(70, 30, 1061, 61))
        self.Thongke_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Thongke_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Thongke_frame.setObjectName("Thongke_frame")
        self.title_lbl = QtWidgets.QLabel(parent=self.Thongke_frame)
        self.title_lbl.setGeometry(QtCore.QRect(30, 10, 1001, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_lbl.setFont(font)
        self.title_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.chon_nam_frame = QtWidgets.QFrame(parent=Form)
        self.chon_nam_frame.setGeometry(QtCore.QRect(70, 110, 521, 50))
        self.chon_nam_frame.setStyleSheet("#chon_name_frame{\n"
"    background-color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.chon_nam_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.chon_nam_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.chon_nam_frame.setObjectName("chon_nam_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.chon_nam_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MH_lbl = QtWidgets.QLabel(parent=self.chon_nam_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MH_lbl.setFont(font)
        self.MH_lbl.setObjectName("MH_lbl")
        self.horizontalLayout.addWidget(self.MH_lbl)
        self.MaMH_line = QtWidgets.QLineEdit(parent=self.chon_nam_frame)
        self.MaMH_line.setObjectName("MaMH_line")
        self.horizontalLayout.addWidget(self.MaMH_line)
        self.label = QtWidgets.QLabel(parent=self.chon_nam_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.loaiBieuDo_comboBox = QtWidgets.QComboBox(parent=self.chon_nam_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loaiBieuDo_comboBox.setFont(font)
        self.loaiBieuDo_comboBox.setObjectName("loaiBieuDo_comboBox")
        self.loaiBieuDo_comboBox.addItem("")
        self.loaiBieuDo_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.loaiBieuDo_comboBox)
        self.pushButton = QtWidgets.QPushButton(parent=self.chon_nam_frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.Bieudo_frame = QtWidgets.QFrame(parent=Form)
        self.Bieudo_frame.setGeometry(QtCore.QRect(70, 170, 1061, 501))
        self.Bieudo_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Bieudo_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Bieudo_frame.setObjectName("Bieudo_frame")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title_lbl.setText(_translate("Form", "THỐNG KÊ ĐIỂM"))
        self.MH_lbl.setText(_translate("Form", "Mã môn học:"))
        self.label.setText(_translate("Form", "Biểu đồ"))
        self.loaiBieuDo_comboBox.setItemText(0, _translate("Form", "Cột"))
        self.loaiBieuDo_comboBox.setItemText(1, _translate("Form", "Tròn"))
        self.pushButton.setText(_translate("Form", "Tìm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
