CREATE DATABASE DULIEU;
USE DULIEU;
DROP DATABASE DULIEU;

CREATE TABLE SINHVIEN(
	MASV VARCHAR(10) NOT NULL,
	HOTEN VARCHAR(50) NOT NULL,
    LOP VARCHAR(10) NOT NULL,
    DCHI VARCHAR(250) NOT NULL,
    NGSINH DATE NOT NULL,
	GTINH VARCHAR(5) NOT NULL,
    SDT VARCHAR(12) NOT NULL,
    PRIMARY KEY (MASV)
);

CREATE TABLE LOP(
	MALOP VARCHAR(10) NOT NULL,
	TENLOP VARCHAR(50) NOT NULL,
    KHOA VARCHAR(50) NOT NULL,
    KHOAHOC VARCHAR(10) NOT NULL,
    HEDAOTAO VARCHAR(100) NOT NULL,
    PRIMARY KEY (MALOP)
);

CREATE TABLE GIANGVIEN(
	MAGV VARCHAR(10) NOT NULL,
    HOTEN VARCHAR(50) NOT NULL,
    NGSINH DATE NOT NULL,
    GTINH VARCHAR(5) NOT NULL,
    KHOA VARCHAR(10) NOT NULL,
    PRIMARY KEY(MAGV)
);


INSERT INTO SINHVIEN (MASV, HOTEN, LOP, DCHI, NGSINH, GTINH, SDT) VALUES (124, 'Tu Anh Phu', 'DCT-1222', 'Q1','2004-02-11', 'Nam', 12345678);
INSERT INTO SINHVIEN (MASV, HOTEN, LOP, DCHI, NGSINH, GTINH, SDT) VALUES (456, 'Nguyen Van Huong', 'DCT-1224', 'Q8','2004-01-12', 'Nu', 12345678);

INSERT INTO LOP (MALOP, TENLOP, KHOA, KHOAHOC, HEDAOTAO) VALUES ('DCT-1222', 'E.205', 'Cong Nghe Thong Tin', '2020', 'Chinh Quy');
INSERT INTO LOP (MALOP, TENLOP, KHOA, KHOAHOC, HEDAOTAO) VALUES ('DCT-1224', 'A.102', 'Tai Chinh', '2020', 'Tu Xa');

INSERT INTO GIANGVIEN (MAGV, HOTEN, NGSINH, GTINH, KHOA) VALUES ('3122', 'LHM', '1996-09-07', 'Nam', 'CNTTK23');
INSERT INTO GIANGVIEN (MAGV, HOTEN, NGSINH, GTINH, KHOA) VALUES ('3123', 'TTS', '1983-09-07', 'Nu', 'CNTTK17');
