CREATE DATABASE DULIEU;
USE DULIEU;
DROP DATABASE DULIEU;

CREATE TABLE SINHVIEN(
	MASV INT NOT NULL,
	HOTEN VARCHAR(50) NOT NULL,
    LOP VARCHAR(50) NOT NULL,
    DCHI VARCHAR(50) NOT NULL,
    NGSINH DATE NOT NULL,
	GTINH VARCHAR(5) NOT NULL,
    SDT INT NOT NULL,
    PRIMARY KEY (MASV)
);

INSERT INTO SINHVIEN (MASV, HOTEN, LOP, DCHI, NGSINH, GTINH, SDT) VALUES (124, 'Tu Anh Phu', 'DCT-1222', 'Q1','2004-02-11', 'Nam', 12345678);
INSERT INTO SINHVIEN (MASV, HOTEN, LOP, DCHI, NGSINH, GTINH, SDT) VALUES (456, 'Nguyen Van Huong', 'DCT-1224', 'Q8','2004-01-12', 'Nu', 12345678);

UPDATE SINHVIEN
SET HOTEN = 'Tran Duc Bo', NGSINH = '1997-03-09'
WHERE MASV = 124

