SELECT K.*, GV.*, NMH.*, MH.*, SV.*, CTBD.*, BD.*
FROM GIANGVIEN AS GV
JOIN KHOA AS K ON K.MAKHOA = GV.KHOA
JOIN LOP AS L ON L.KHOA = K.MAKHOA
JOIN NHOMMONHOC AS NMH ON NMH.GV = GV.MAGV
JOIN MONHOC AS MH ON MH.MAMH = NMH.MH
JOIN CHITIETBANGDIEM AS CTBD ON CTBD.NHOM = NMH.MANHOM
JOIN BANGDIEM AS BD ON BD.MABD = CTBD.BD
JOIN SINHVIEN AS SV ON SV.MASV = BD.SV AND SV.LOP = L.MALOP
JOIN DANGKYNHOM AS DKN ON DKN.SV = SV.MASV AND DKN.NHOM = NMH.MANHOM
-- WHERE 
-- GV.MAGV LIKE 'GV01001'
-- AND NMH.MANHOM LIKE 'N010201'
-- AND NMH.MH LIKE '2010002'
AND SV.MASV LIKE '222010001';

UPDATE CHITIETBANGDIEM CTBD
JOIN BANGDIEM BD ON CTBD.BD = BD.MABD
JOIN SINHVIEN SV ON SV.MASV = BD.SV
JOIN NHOMMONHOC NMH ON NMH.MANHOM = CTBD.NHOM
JOIN MONHOC MH ON NMH.MH = MH.MAMH
JOIN GIANGVIEN GV ON GV.MAGV = NMH.GV
JOIN KHOA K ON GV.KHOA = K.MAKHOA
JOIN LOP L ON L.KHOA = K.MAKHOA AND SV.LOP = L.MALOP
JOIN DANGKYNHOM DKN ON DKN.NHOM = NMH.MANHOM AND DKN.SV = SV.MASV
SET 
    CTBD.DIEM_QT = 10,
    CTBD.HESO_QT = 0.5, 
    CTBD.DIEMTHI = 10,
    CTBD.HESO_THI = 0.5,
    CTBD.DIEMTB_HE10 = 10,
    CTBD.DIEMTB_HE4 = 4,
    CTBD.XEPLOAI = 'A'
WHERE 
    GV.MAGV LIKE 'GV01001'
    AND NMH.MANHOM = 'N010201'
    AND MH.MAMH = '2010002'
    AND SV.MASV = '222010001';
    
UPDATE BANGDIEM
    JOIN SINHVIEN AS SV ON SV.MASV = BD.SV
    JOIN NHOMMONHOC AS NMH ON NMH.MANHOM = CHITIETBANGDIEM.NHOM
    JOIN MONHOC AS MH ON NMH.MH = MH.MAMH
    JOIN GIANGVIEN AS GV ON GV.MAGV = NMH.GV
    JOIN KHOA AS K ON GV.KHOA = K.MAKHOA
    JOIN LOP AS L ON L.KHOA = K.MAKHOA AND SV.LOP = L.MALOP
    JOIN DANGKYNHOM AS DKN ON DKN.NHOM = NMH.MANHOM AND DKN.SV = SV.MASV
SET
	BD.
WHERE
    GV.MAGV LIKE 'GV01001'
    AND NMH.MANHOM = 'N010201'
    AND MH.MAMH = '2010002'
    AND SV.MASV = '222010001';

    
SELECT *
FROM ACCOUNT
WHERE USERNAME = '222010001';

SELECT CTBD.DIEMTB_HE10 
FROM BANGDIEM BD, CHITIETBANGDIEM CTBD 
WHERE BD.MASV = '222010001' AND BD.MABD = CTBD.BD;

SELECT sinhvien.MASV, sinhvien.HOTEN, sinhvien.NGSINH, sinhvien.GTINH, sinhvien.SDT, sinhvien.DCHI, sinhvien.LOP, khoa.TENKHOA
from sinhvien, lop, khoa
where sinhvien.LOP = lop.MALOP and lop.KHOA = khoa.MAKHOA and MASV = '222010001';

SELECT K.*
FROM KHOA K
WHERE K.TRGKHOA = 'GV01001';

SELECT ACC.USERNAME, ACC.PASS
FROM ACCOUNT ACC
WHERE ACC.USERNAME = '222010001';

SELECT SUM(MH.SOTC), SUM(CTBD.DIEMTB_HE10 *MH.SOTC), SUM(CTBD.DIEMTB_HE4 *MH.SOTC)
FROM SINHVIEN SV
JOIN BANGDIEM BD ON SV.MASV = BD.SV 
JOIN CHITIETBANGDIEM CTBD ON CTBD.BD = BD.MABD
JOIN NHOMMONHOC NMH ON CTBD.NHOM = NMH.MANHOM
JOIN DANGKYNHOM DKN ON DKN.NHOM =  NMH.MANHOM AND DKN.SV = SV.MASV
JOIN MONHOC MH ON MH.MAMH = NMH.MH
WHERE SV.MASV = '222010002'
AND BD.HOCKY = '2'
AND BD.NAMHOC = '2024';

SELECT BD.*, MH.*, CTBD.*
FROM SINHVIEN SV
JOIN BANGDIEM BD ON SV.MASV = BD.SV 
JOIN CHITIETBANGDIEM CTBD ON CTBD.BD = BD.MABD
JOIN NHOMMONHOC NMH ON CTBD.NHOM = NMH.MANHOM
JOIN DANGKYNHOM DKN ON DKN.NHOM =  NMH.MANHOM AND DKN.SV = SV.MASV
JOIN MONHOC MH ON MH.MAMH = NMH.MH
WHERE SV.MASV = '222010002'
AND BD.HOCKY = '2'
AND BD.NAMHOC = '2024';

UPDATE BANGDIEM BD
JOIN SINHVIEN SV ON SV.MASV = BD.SV 
JOIN CHITIETBANGDIEM CTBD ON CTBD.BD = BD.MABD
JOIN NHOMMONHOC NMH ON CTBD.NHOM = NMH.MANHOM
JOIN DANGKYNHOM DKN ON DKN.NHOM = NMH.MANHOM AND DKN.SV = SV.MASV
JOIN MONHOC MH ON MH.MAMH = NMH.MH
SET BD.DIEMTK_HE10 = '', BD.DIEMTK_HE4 = '' 
WHERE SV.MASV = '';







