SELECT K.*, GV.*, NMH.*, MH.*, SV.*, CTBD.*, BD.*
FROM GIANGVIEN GV
JOIN KHOA K ON K.MAKHOA = GV.KHOA
JOIN LOP L ON L.KHOA = K.MAKHOA
JOIN NHOMMONHOC NMH ON NMH.GV = GV.MAGV
JOIN MONHOC MH ON MH.MAMH = NMH.MH
JOIN CHITIETBANGDIEM CTBD ON CTBD.NHOM = NMH.MANHOM
JOIN BANGDIEM BD ON BD.MABD = CTBD.BD
JOIN SINHVIEN SV ON SV.MASV = BD.SV AND SV.LOP = L.MALOP
JOIN DANGKYNHOM DKN ON DKN.SV = SV.MASV AND DKN.NHOM = NMH.MANHOM
WHERE GV.MAGV LIKE 'GV01001'
AND NMH.MANHOM LIKE 'N010201'
AND NMH.MH LIKE '2010002'
AND SV.MASV LIKE '222010001';

SELECT DISTINCT CTBD.*
FROM CHITIETBANGDIEM CTBD
JOIN BANGDIEM BD ON CTBD.BD = BD.MABD
JOIN SINHVIEN SV ON SV.MASV = BD.MASV
JOIN NHOMMONHOC NMH ON NMH.MANHOM = CTBD.MANHOM
JOIN MONHOC MH ON NMH.MH = MH.MAMH
JOIN GIANGVIEN GV ON GV.MAGV = NMH.GV
JOIN KHOA K ON GV.KHOA = K.MAKHOA
JOIN LOP L ON L.KHOA = K.MAKHOA
JOIN DANGKYNHOM DKN ON DKN.NHOM = NMH.MANHOM
WHERE -- GV.MAGV =  '' AND
MH.MAMH = '2010002'
AND CTBD.MANHOM = 'N010201'
AND SV.MASV = '222010001';



UPDATE CHITIETBANGDIEM CTBD
JOIN BANGDIEM BD ON CTBD.BD = BD.MABD
JOIN SINHVIEN SV ON SV.MASV = BD.MASV
JOIN NHOMMONHOC NMH ON NMH.MANHOM = CTBD.MANHOM
JOIN MONHOC MH ON NMH.MH = MH.MAMH
JOIN GIANGVIEN GV ON GV.MAGV = NMH.GV
JOIN KHOA K ON GV.KHOA = K.MAKHOA
JOIN LOP L ON L.KHOA = K.MAKHOA
JOIN DANGKYNHOM DKN ON DKN.NHOM = NMH.MANHOM
SET 
    CTBD.DIEM_QT = '10',
    CTBD.HESO_QT = '0.5',
    CTBD.DIEMTHI = '10',
    CTBD.HESO_THI = '0.5',
    CTBD.DIEMTB_HE10 = ('10' * '0.5') + ('10' * '0.5')
WHERE 
    MH.MAMH = '2010002'
    AND CTBD.MANHOM = 'N010201'
    AND SV.MASV = '222010001';
    
SELECT *
FROM ACCOUNT
WHERE USERNAME = '222010001';

SELECT CTBD.DIEMTB_HE10 
FROM BANGDIEM BD, CHITIETBANGDIEM CTBD 
WHERE BD.MASV = '222010001' AND BD.MABD = CTBD.BD;

SELECT sinhvien.MASV, sinhvien.HOTEN, sinhvien.NGSINH, sinhvien.GTINH, sinhvien.SDT, sinhvien.DCHI, sinhvien.LOP, khoa.TENKHOA
from sinhvien, lop, khoa
where sinhvien.LOP = lop.MALOP and lop.KHOA = khoa.MAKHOA and MASV = '222010001';

SELECT K.*
FROM KHOA K
WHERE K.TRGKHOA = 'GV01001';

SELECT ACC.USERNAME, ACC.PASS
FROM ACCOUNT ACC
WHERE ACC.USERNAME = '222010001';

SELECT BD.*, MH.*, CTBD.*
FROM SINHVIEN SV
JOIN BANGDIEM BD ON SV.MASV = BD.SV 
JOIN CHITIETBANGDIEM CTBD ON CTBD.BD = BD.MABD
JOIN NHOMMONHOC NMH ON CTBD.NHOM = NMH.MANHOM
JOIN DANGKYNHOM DKN ON DKN.NHOM =  NMH.MANHOM AND DKN.SV = SV.MASV
JOIN MONHOC MH ON MH.MAMH = NMH.MH
WHERE SV.MASV = '222010001'
AND BD.HOCKY = '2'
AND BD.NAMHOC = '2024';







