CREATE DATABASE TEST;
USE TEST;
DROP DATABASE TEST;

CREATE TABLE ACC(
	USERNAME VARCHAR(10),
    PASS VARCHAR(10),
    PRIMARY KEY (USERNAME)
);

INSERT INTO ACC (USERNAME, PASS) VALUES
('ABC', '1'),
('fgd', '1'),
('legen', '2'),
('717', '1');