# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Menu(object):
    def setupMenu(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.Menu_Frame = QtWidgets.QWidget(parent=Form)
        self.Menu_Frame.setStyleSheet("#Menu_Frame{\n"
"    background-color: cyan;\n"
"}")
        self.Menu_Frame.setObjectName("Menu_Frame")
        self.gridLayout = QtWidgets.QGridLayout(self.Menu_Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.Menu_Frame)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.AdminBtn = QtWidgets.QPushButton(parent=self.Menu_Frame)
        self.AdminBtn.setObjectName("AdminBtn")
        self.verticalLayout.addWidget(self.AdminBtn)
        self.GVBtn = QtWidgets.QPushButton(parent=self.Menu_Frame)
        self.GVBtn.setObjectName("GVBtn")
        self.verticalLayout.addWidget(self.GVBtn)
        self.SVBtn = QtWidgets.QPushButton(parent=self.Menu_Frame)
        self.SVBtn.setObjectName("SVBtn")
        self.verticalLayout.addWidget(self.SVBtn)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 244, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.Menu_Frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Menu_Frame)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setStyleSheet("#Ad_Frame {\n"
"background-color: pink;\n"
"}\n"
"#GV_Frame {\n"
"background-color: yellow\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Frame_Admin = QtWidgets.QWidget()
        self.Frame_Admin.setObjectName("Frame_Admin")
        self.Ad_Frame = QtWidgets.QFrame(parent=self.Frame_Admin)
        self.Ad_Frame.setGeometry(QtCore.QRect(120, 30, 271, 161))
        self.Ad_Frame.setStyleSheet("")
        self.Ad_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Ad_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Ad_Frame.setObjectName("Ad_Frame")
        self.stackedWidget.addWidget(self.Frame_Admin)
        self.fr = QtWidgets.QWidget()
        self.fr.setObjectName("fr")
        self.GV_Frame = QtWidgets.QFrame(parent=self.fr)
        self.GV_Frame.setGeometry(QtCore.QRect(120, 50, 271, 161))
        self.GV_Frame.setStyleSheet("#Admin_Frame{\n"
"    background-color: grey;\n"
"}")
        self.GV_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.GV_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.GV_Frame.setObjectName("GV_Frame")
        self.stackedWidget.addWidget(self.fr)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.widget_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "MENU"))
        self.AdminBtn.setText(_translate("Form", "Admin"))
        self.GVBtn.setText(_translate("Form", "Giao Vien"))
        self.SVBtn.setText(_translate("Form", "Sinh Vien"))
        self.pushButton.setText(_translate("Form", "Thoat"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec())
