# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class login (object):
    def setuplogin(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setAutoFillBackground(False)
        self.avt = QtWidgets.QFrame(Dialog)
        self.avt.setGeometry(QtCore.QRect(0, 0, 200, 400))
        self.avt.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.avt.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.avt.setStyleSheet("background-color: #006696;")
        self.avt.setObjectName("avt")
        self.label_7 = QtWidgets.QLabel(self.avt)
        self.label_7.setGeometry(QtCore.QRect(40, 90, 120, 120))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../Downloads/avt_fb.webp"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.avt)
        self.label_8.setGeometry(QtCore.QRect(10, 200, 180, 80))
        self.label_8.setStyleSheet("font-size: 15px; color: white;")
        self.label_8.setObjectName("label_8")
        self.label_8.setText("<b>Bold Text</b>")

        self.form_signup = QtWidgets.QFrame(Dialog)
        self.form_signup.setGeometry(QtCore.QRect(200, 0, 400, 400))
        self.form_signup.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.form_signup.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.form_signup.setStyleSheet("background-color: #70b9dc;")
        self.form_signup.setObjectName("form_signup")

        self.label = QtWidgets.QLabel(self.form_signup)
        self.label.setGeometry(QtCore.QRect(100, 30, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setText("<b>Bold Text</b>")
        self.label.setStyleSheet("color: #006696;")
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.form_signup)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 140, 30))
        self.label_2.setStyleSheet("font-size: 18px; color: #006696;")
        self.label_2.setText("<b>Bold Text</b>")
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.form_signup)
        self.label_3.setGeometry(QtCore.QRect(65, 220, 115, 30))
        self.label_3.setStyleSheet("font-size: 18px; color: #006696;")
        self.label_3.setText("<b>Bold Text</b>")
        self.label_3.setObjectName("label_3")

        self.userentry = QtWidgets.QLineEdit(parent=self.form_signup)
        self.userentry.setGeometry(QtCore.QRect(180, 120, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userentry.setFont(font)
        self.userentry.setText("")
        self.userentry.setStyleSheet("border: 1px solid #006696; background-color: white; ")
        self.userentry.setObjectName("userentry")

        self.passentry = QtWidgets.QLineEdit(parent=self.form_signup)
        self.passentry.setGeometry(QtCore.QRect(180, 220, 180, 30))
        self.passentry.setFont(font)
        self.passentry.setText("")
        self.passentry.setStyleSheet("border: 1px solid #006696; background-color: white; ")
        self.passentry.setObjectName("passentry")

        self.label_5 = QtWidgets.QLabel(self.form_signup)
        self.label_5.setGeometry(QtCore.QRect(190, 155, 140, 20))
        self.label_5.setStyleSheet("font-size: 12px; color: red;")
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.form_signup)
        self.label_6.setGeometry(QtCore.QRect(190, 255, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-size: 12px; color: red;")
        self.label_6.setObjectName("label_6")

        self.log_in = QtWidgets.QPushButton(self.form_signup)
        self.log_in.setGeometry(QtCore.QRect(210, 350, 70, 30))
        self.log_in.setStyleSheet("border: 1px solid white; background-color: #006696; color: white; ")
        self.log_in.setText("<b>Bold Text</b>")
        self.log_in.setObjectName("pushButton")

        self.exit = QtWidgets.QPushButton(self.form_signup)
        self.exit.setGeometry(QtCore.QRect(290, 350, 70, 30))
        self.exit.setStyleSheet("border: 1px solid white; background-color: #006696; color: white; ")
        self.exit.setText("<b>Bold Text</b>")
        self.exit.setObjectName("pushButton_2")

        self.form_signup.raise_()
        self.avt.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_8.setText(_translate("Dialog", "QUẢN LÝ ĐIỂM SINH VIÊN"))
        self.label_6.setText(_translate("Dialog", "́*Không được bỏ trống"))
        self.log_in.setText(_translate("Dialog", "LOG IN"))
        self.exit.setText(_translate("Dialog", "CANCEL"))
        self.label_5.setText(_translate("Dialog", "́*Không được bỏ trống"))
        self.label_3.setText(_translate("Dialog", "Mật khẩu:"))
        self.label_2.setText(_translate("Dialog", "Tên đăng nhập:"))
        self.label.setText(_translate("Dialog", "ĐĂNG NHẬP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = login()
    ui.setuplogin(Dialog)
    Dialog.show()
    sys.exit(app.exec())
